[project]
name = "nrs_einvoice"
authors = [{ name = "Raavon Limited" }]
description = "NRS (Nigeria Revenue Service) MBS e-invoicing for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = ["qrcode>=7.4", "cryptography"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
